# Generated by Django 4.1.7 on 2023-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="country_code",
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="country_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="driver_abbreviation",
            field=models.CharField(
                blank=True, max_length=3, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
