# Generated by Django 4.1.7 on 2023-03-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0002_alter_country_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="tean_principal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tean_principal",
                to="personnel.person",
            ),
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=50)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personnel.person",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personnel.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="team_members",
            field=models.ManyToManyField(
                through="personnel.TeamMember", to="personnel.person"
            ),
        ),
    ]
