# Generated by Django 4.1.7 on 2023-03-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0003_team_tean_principal_teammember_team_team_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="team",
        ),
        migrations.RemoveField(
            model_name="team",
            name="team_members",
        ),
        migrations.AddField(
            model_name="team",
            name="team_members",
            field=models.ManyToManyField(to="personnel.teammember"),
        ),
    ]
