# Generated by Django 4.1.7 on 2023-03-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0004_remove_teammember_team_alter_team_team_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
        migrations.RemoveField(
            model_name="team",
            name="team_members",
        ),
        migrations.RemoveField(
            model_name="team",
            name="tean_principal",
        ),
        migrations.AddField(
            model_name="team",
            name="team_principal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_principal",
                to="personnel.person",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="personnel.team",
            ),
            preserve_default=False,
        ),
    ]
