# Generated by Django 4.1.7 on 2023-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0006_alter_teammember_team"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("team", "person"), name="Unique employee"
            ),
        ),
    ]
