# Generated by Django 4.1.7 on 2023-03-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0009_alter_teammember_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="personnel.person",
            ),
        ),
    ]
