# Generated by Django 4.1.7 on 2023-03-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0011_remove_person_driver_abbreviation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_principal",
                to="personnel.person",
            ),
        ),
    ]
