# Generated by Django 4.1.7 on 2023-03-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tyrecompound",
            name="Unique tyre producer-compound",
        ),
    ]
