# Generated by Django 4.1.7 on 2023-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mechanical",
            "0002_remove_tyrecompound_unique tyre producer-compound",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tyrecompound",
            constraint=models.UniqueConstraint(
                fields=("producer", "compound_name"),
                name="Unique tyre producer-compound",
            ),
        ),
    ]
