# Generated by Django 4.1.7 on 2023-03-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical", "0004_engine_teamcar_drivercar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverCar",
        ),
    ]
